# Nelmio CORS Configuration
#nelmio_cors:
#    defaults:
#        allow_credentials: false
#        allow_origin: ['*']
#        allow_headers: ['*']
#        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
#        max_age: 3600
#        hosts: []
#        origin_regex: false
 
# FOSRest Configuration
#fos_rest:
#    body_listener: true
#    view:
#        view_response_listener: true
#    serializer:
#        serialize_null: true
#    body_converter:
#        enabled: true
#        format_listener:
#            rules:
#              - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: true }
#              - { path: '^/', priorities: ['html', '*/*'], fallback_format: html, prefer_extension: true }

fos_rest:
    routing_loader:
        default_format: json
        include_format: false
    body_listener: true
   # format_listener:
   #       rules:
   #           - { path: '^/', priorities: ['json'], fallback_format: json, prefer_extension: false }
    param_fetcher_listener: true
    access_denied_listener:
        json: true
    view:
        view_response_listener: 'force'
        formats:
            json: true

jms_serializer:
    property_naming:
        separator:  _
        lower_case: true

    metadata:
        cache: file
        debug: "%kernel.debug%"
        file_cache:
            dir: "%kernel.cache_dir%/serializer"
        directories:
            FOSUserBundle:
                namespace_prefix: FOS\UserBundle
                path: %kernel.root_dir%/config/serializer/FosUserBundle
            AppBundle:
                namespace_prefix: AppBundle
                path: %kernel.root_dir%/config/serializer/AppBundle
        auto_detection: true